on:
  push:
    branches:
      - main
name: Deploy to the Production Environment on main Branch
jobs:
  web-deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Use Production env
      run: cp env.production .env
        
    - name: Install vendors
      run: |
          composer install --prefer-dist --no-dev --optimize-autoloader
          rm -rf node_modules package-lock.json
          npm install
          npm run build
          npm ci --no-optional

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: pdx1-shared-a4-04.dreamhost.com
        username: dh_3hffj8
        password: oA12?1K?5V
        timeout_minutes : 1
        max_attempts : 3
        server-dir: system.smartsyndicates.lk/

    - name: Check website status
      run: curl -I https://system.smartsyndicates.lk