<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $invoice->invoice_number }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            border-bottom: 2px solid #2563eb;
            margin-bottom: 20px;
            padding-bottom: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .header img {
            height: 50px;
        }
        .header h1 {
            font-size: 20px;
            margin: 0;
            color: #2563eb;
        }
        .invoice-info, .site-info {
            margin-bottom: 20px;
        }
        .invoice-info table, .site-info table {
            width: 100%;
        }
        .invoice-info td, .site-info td {
            padding: 3px 0;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .table th {
            background-color: #f3f4f6;
            color: #111827;
        }
        .total-section {
            text-align: right;
            margin-top: 20px;
        }
        .status {
            display: inline-block;
            padding: 4px 10px;
            border-radius: 6px;
            text-transform: capitalize;
            font-weight: bold;
            color: white;
        }
        .status.draft { background-color: #9ca3af; }
        .status.sent { background-color: #3b82f6; }
        .status.paid { background-color: #10b981; }
        .status.cancelled { background-color: #ef4444; }

        footer {
            border-top: 1px solid #ddd;
            margin-top: 30px;
            padding-top: 10px;
            text-align: center;
            font-size: 11px;
            color: #6b7280;
        }
    </style>
</head>
<body>
    {{-- HEADER --}}
    <div class="header">
        <div>
            <h1>Invoice</h1>
            <p style="margin: 0; font-size: 14px;">{{ config('app.name', 'Security System') }}</p>
        </div>
        <div>
            {{-- Update logo path if available --}}
            <img src="{{ public_path('images/logo.png') }}" alt="Company Logo">
        </div>
    </div>

    {{-- INVOICE DETAILS --}}
    <div class="invoice-info">
        <table>
            <tr>
                <td><strong>Invoice No:</strong> {{ $invoice->invoice_number }}</td>
                <td><strong>Date:</strong> {{ $invoice->invoice_date->format('Y-m-d') }}</td>
            </tr>
            <tr>
                <td><strong>Status:</strong> <span class="status {{ $invoice->status }}">{{ $invoice->status }}</span></td>
                <td><strong>Generated On:</strong> {{ now()->format('Y-m-d H:i') }}</td>
            </tr>
        </table>
    </div>

    {{-- SITE INFO --}}
    <div class="site-info">
        <table>
            <tr>
                <td><strong>Site:</strong> {{ $invoice->site->name ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td><strong>Description:</strong> {{ $invoice->description ?? '—' }}</td>
            </tr>
        </table>
    </div>

    {{-- INVOICE ITEMS --}}
    <table class="table">
        <thead>
            <tr>
                <th>Guard</th>
                <th>Days</th>
                <th>Rate (£)</th>
                <th>Subtotal (£)</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($invoice->items as $item)
                <tr>
                    <td>{{ $item->employee->name ?? 'N/A' }}</td>
                    <td>{{ $item->days }}</td>
                    <td>£{{ number_format($item->rate, 2) }}</td>
                    <td>£{{ number_format($item->subtotal, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {{-- TOTAL --}}
    <div class="total-section">
        <h3>Total Amount: £{{ number_format($invoice->total_amount, 2) }}</h3>
    </div>

    {{-- FOOTER --}}
    <footer>
        {{ config('app.name', 'Security System') }} &bull; Generated by system on {{ now()->format('Y-m-d H:i') }}
    </footer>
</body>
</html>
